/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ApplyTemplateModal: typeof import('./src/components/project/ApplyTemplateModal.vue')['default']
    AssigneePicker: typeof import('./src/components/assignment/AssigneePicker.vue')['default']
    AvatarStack: typeof import('./src/components/common/AvatarStack.vue')['default']
    Breadcrumb: typeof import('./src/components/common/Breadcrumb.vue')['default']
    BudgetBurnRate: typeof import('./src/components/gantt/BudgetBurnRate.vue')['default']
    CascadePreview: typeof import('./src/components/gantt/CascadePreview.vue')['default']
    CreateMilestoneModal: typeof import('./src/components/project/CreateMilestoneModal.vue')['default']
    CreateTaskModal: typeof import('./src/components/project/CreateTaskModal.vue')['default']
    DeleteProjectModal: typeof import('./src/components/project/DeleteProjectModal.vue')['default']
    DependencyChain: typeof import('./src/components/gantt/DependencyChain.vue')['default']
    DockDiscussionsTab: typeof import('./src/components/manager/tabs/DockDiscussionsTab.vue')['default']
    EmptyState: typeof import('./src/components/common/EmptyState.vue')['default']
    FormField: typeof import('./src/components/common/FormField.vue')['default']
    GanttChart: typeof import('./src/components/gantt/GanttChart.vue')['default']
    GanttFocusPanel: typeof import('./src/components/gantt/GanttFocusPanel.vue')['default']
    KanbanColumnQuickAdd: typeof import('./src/components/project/KanbanColumnQuickAdd.vue')['default']
    LinkInput: typeof import('./src/components/common/LinkInput.vue')['default']
    LoadingButton: typeof import('./src/components/common/LoadingButton.vue')['default']
    ManagerHeader: typeof import('./src/components/manager/ManagerHeader.vue')['default']
    ManagerTabContent: typeof import('./src/components/manager/ManagerTabContent.vue')['default']
    ManagerTabs: typeof import('./src/components/manager/ManagerTabs.vue')['default']
    MigrationPanel: typeof import('./src/components/MigrationPanel.vue')['default']
    OrgaIcon: typeof import('./src/components/common/OrgaIcon.vue')['default']
    PortalHeader: typeof import('./src/components/layout/PortalHeader.vue')['default']
    PortalLayout: typeof import('./src/components/layout/PortalLayout.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SaveAsTemplateModal: typeof import('./src/components/project/SaveAsTemplateModal.vue')['default']
    SearchDropdown: typeof import('./src/components/SearchDropdown.vue')['default']
    Skeleton: typeof import('./src/components/common/Skeleton.vue')['default']
    StatusBadge: typeof import('./src/components/common/StatusBadge.vue')['default']
    TaskActionsTab: typeof import('./src/components/manager/tabs/TaskActionsTab.vue')['default']
    TaskAttachmentsTab: typeof import('./src/components/manager/tabs/TaskAttachmentsTab.vue')['default']
    TaskChecklistTab: typeof import('./src/components/manager/tabs/TaskChecklistTab.vue')['default']
    TaskDependenciesTab: typeof import('./src/components/manager/tabs/TaskDependenciesTab.vue')['default']
    TaskDetailsTab: typeof import('./src/components/manager/tabs/TaskDetailsTab.vue')['default']
    TaskFinanceTab: typeof import('./src/components/manager/tabs/TaskFinanceTab.vue')['default']
    TaskManager: typeof import('./src/components/TaskManager.vue')['default']
    ToastContainer: typeof import('./src/components/common/ToastContainer.vue')['default']
    UserAvatar: typeof import('./src/components/common/UserAvatar.vue')['default']
    UserMenu: typeof import('./src/components/layout/UserMenu.vue')['default']
    WatchTimeTab: typeof import('./src/components/manager/tabs/WatchTimeTab.vue')['default']
  }
}
